/**
 * generated by Xtext 2.29.0
 */
package org.example.entities.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EntitiesIdeModule extends AbstractEntitiesIdeModule {
}
