/**
 * generated by Xtext 2.29.0
 */
package org.example.entities.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EntitiesUiModule extends AbstractEntitiesUiModule {
  public EntitiesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
