/*
 * generated by Xtext 2.29.0
 */
package org.example.entities.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.example.entities.ui.internal.EntitiesActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EntitiesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EntitiesActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EntitiesActivator activator = EntitiesActivator.getInstance();
		return activator != null ? activator.getInjector(EntitiesActivator.ORG_EXAMPLE_ENTITIES_ENTITIES) : null;
	}

}
